site_name: Homelab Documentation
site_url: https://kcn3333.github.io/homelab/
repo_url: https://github.com/kCn3333/homelab
repo_name: kCn3333/homelab
edit_uri: edit/main/docs/
docs_dir: docs

theme:
  name: material
  language: en
  icon:
    logo: material/server-network
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: custom
      accent: custom
  
  features:
    - announce.dismiss
    #- content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    #- navigation.expand
    #- navigation.footer         
    #- navigation.indexes
    #- navigation.instant
    #- navigation.instant.prefetch
    #- navigation.instant.progress
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    #- search.highlight
    #- search.share
    #- search.suggest
    - toc.follow

plugins:
  - awesome-pages
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - roamlinks
  - callouts
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
      
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      #pygments_style: one-dark 
      use_pygments: true  # 
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: kCn3333
      repo: homelab
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kCn3333
  generator: false

extra_css:
  - stylesheets/retro.css
  #- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css

#extra_javascript:
 # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
 # - javascripts/hljs-init.js
 # - javascripts/matrix-homelab.js


nav:
  - material/home "Home": index.md


  - material/excavator "Infrastructure": 
    - material/server-network "network":  infrastructure/home.md
    - ":material-hammer-screwdriver: project server": https://kcn333.pl/home_server

  - octicons/rocket-24  "Provisioning": provisioning
  

  - material/application-cog "Applications":
      
    - ":simple-docker: Docker Compose Repo": https://github.com/kCn3333/docker-compose
    - ":octicons-terminal-24: .bashrc": https://github.com/kCn3333/linux-bash/blob/main/.bashrc
    - ":fontawesome-regular-folder-open: Bash Scripts": 
      - ":simple-gnometerminal: backup": https://github.com/kCn3333/linux-bash/tree/main/backup
      - ":simple-gnometerminal: db backup": https://github.com/kCn3333/linux-bash/tree/main/db_backup
      - ":simple-gnometerminal: ssh login alert": https://github.com/kCn3333/linux-bash/tree/main/ssh_login_alert
      - ":simple-gnometerminal: temp monitor": https://github.com/kCn3333/linux-bash/tree/main/temp_monitor
    - ":simple-starship: starship config": https://github.com/kCn3333/starship-config
    - ":octicons-file-code-24: conky config": https://github.com/kCn3333/linux-conky/blob/main/conky.conf
    - ":material-shark-fin-outline: wireshark config": https://github.com/kCn3333/wireshark


  - ":simple-inductiveautomation: Automation": 
    - ":material-ansible: Ansible playbooks": automation
    - ":simple-stackshare: n8n workflows": https://github.com/kCn3333/n8n_workflows
      
  - ":material-bug-check: Troubleshooting": troubleshooting


copyright: |
  <div style="text-align: center; margin-top: 1rem;">
    <p style="color: #E0E0E0; font-style: italic; margin-bottom: 0.5rem;">
      Built with coffee, curiosity, and so much fun © kCn 2025 ✌︎︎  
    </p>
  </div>